### ISSUE TITLE
Separate loading and data massaging from display

### ISSUE THREAD

**Issue by mbleigh** [PolymerElements/iron-doc-viewer#1]
Hydrolysis by itself gives a thorough but very rough representation of the data necessary for displaying documentation. I'm finding myself re-implementing large swaths of `iron-doc-viewer` code in order to customize the appearance and interaction.

My suggestion: implement an `iron-doc-loader` that takes the raw hydrolysis data and massages it into display-ready doc content. Basically bring the `_descriptorChanged` from `iron-doc-element` and `iron-doc-property` and the `load` and `_processRoot` from `iron-doc-viewer` into a new element (suggestion: `icon-doc-loader`).

If it did all the data processing up front, it could just expose a clean object something like:

``` json
{
  "elements": [
    {
      "is":"example-element",
      "properties":[{"name":"attr","type":"String","default":"bute","private":false}],
      "methods":[{"name":"_privateMethod"}],
      "events":[]
    }
  ]
}
```

If not, it could at least provide an API for the canonical data-massaging desired.

**Comment by nevir** [comment]
Hmm, well, the alternative is for us to clean up the hydrolysis output a
bit, so that each iron-doc-\* element can consume the descriptors with no
change. (But yeah, this current approach is brittle!)

What kinds of customizations are you making? Can I also provide hooks or
decompose further to make that easier?

**Comment by mbleigh** [comment]
Yeah, cleaning up hydrolysis output is also fine (didn't know if there was a plan for hydrolysis to be a more generalized parsing tool that didn't want to know too many Polymer specifics).

Since we're building the catalog and a primary function of the catalog is displaying documentation, it seems like it'd be a difficult task to provide enough customization or decomposition to make it doable. At the end of the day a lot of it's just going to be styling and markup structure, but that's pretty tough to allow for customization. Only way I can think would be something like:

``` html
<iron-doc-viewer src="foo.html">
  <template ref="element">
  </template>
  <template ref="property">
  </template>
</iron-doc-viewer>
```

Where you can literally provide replacement templates. Seems like an unnecessary burden on this repo though, probably easier just to be able to consume the data directly.

I'd say my first choice after some thought would be hydrolysis output being render-ready and adding a declarative element for loading hydrolysis data to avoid needing to write boilerplate loader code (in the hydrolysis repo e.g. `<hydrolysis-loader src="foo.html">` or `<hydrolysis-loader html="[[someRawHTML]]">`.

**Comment by nevir** [comment]
> Yeah, cleaning up hydrolysis output is also fine (didn't know if there was a plan for hydrolysis to be a more generalized parsing tool that didn't want to know too many Polymer specifics).

We see hydrolysis as the basis for a bunch of our current and future tooling (docs, concatenation, static analysis, code formatting, etc, etc). I think it makes sense to give it some heavier logic (as an opt-in transformation).

I'm waffling as to whether it should be something like `hydrolysis.docs.getElements(rootImport)`, or whether we should bake the knowledge into the existing docs functions. (have any leaning there @garlicnation?)

The current behavior is to layer the data on, but I think it's time to start replacing it when you call into `hydrolysis.docs.*`. (layering it is becoming too cumbersome). Something like:
- Annotate properties with `private` if they begin with `_`, or are tagged `@private`
- Override the property `type` with the `@type` expression, if given.
- Expand out any other JSDoc tags that modify the meaning of a property.

**Comment by nevir** [comment]
> I'd say my first choice after some thought would be hydrolysis output being render-ready and adding a declarative element for loading hydrolysis data to avoid needing to write boilerplate loader code.

That seems reasonable to me! Maybe we should package that element w/ hydrolysis proper, hmm.

**Comment by mbleigh** [comment]
Yeah that's what I was thinking made the most sense.
