### ISSUE TITLE
New iron-doc-viewer (analyzer-2 branch) doesn't sort members

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/iron-doc-viewer#107]
Polymer 1, properties and methods sorted:

https://www.polymer-project.org/1.0/docs/api/Polymer.Base

Polymer 2: methods, namespaces, etc. in random order:

https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element

**Comment by aomarks** [comment]
Fixed on `analyzer-2.0`.
