### ISSUE TITLE
No space between "with" and Mixin name

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/iron-doc-viewer#108]
See for example:

![image](https://cloud.githubusercontent.com/assets/1149422/24635724/2d97f082-188a-11e7-9407-3ddb3d002bad.png)

In theory this should be fixed by https://github.com/PolymerElements/iron-doc-viewer/commit/cf52573896b17c209c26109320fe8c4bf81152ad, but in practice it is not. I think either the HTML minification or some magic on the part of the `<template is="dom-repeat"` is removing the space. 

Adding a zero-width space before the template appears to prevent this problem.

`with &#8203;<template is="dom-repeat" ...>`

**Comment by aomarks** [comment]
Fixed in 3.x branch.
