### ISSUE TITLE
HTML tags referenced in API docs should be escaped

### ISSUE THREAD

**Issue by kevinpschaaf** [PolymerElements/iron-doc-viewer#118]
### Description
HTML tags referenced in API docs should be escaped.  Although code snippits that include HTML should generally be in backticks to ensure they are rendered with code formatting, failing to do so results in rendering and could present an XSS vulnerability.

### Live repro
See https://www.polymer-project.org/2.0/docs/api/mixins/Polymer.TemplateStamp

### Expected outcome
All API docs rendered correctly

### Actual outcome
![image](https://cloud.githubusercontent.com/assets/1354932/25399027/e67b6998-29a2-11e7-9869-91e51572c1ea.png)

### Version
2.0-preview

**Comment by justinfagnani** [comment]
I _think_ we may be able to fix this by just putting `sanitize="true"` on all uses of `marked-element`.

**Comment by aomarks** [comment]
Fixed on 2.0-analyzer.
