### ISSUE TITLE
Support class docs

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/iron-doc-viewer#122]
I believe as of https://github.com/Polymer/polymer-analyzer/pull/625 the analyzer has support for classes, but I think they probably need their own doc element here. (And we need to  update the API doc script in the docs repo to pull out the classes.)

Currently we have a number of things (Polymer.Debouncer, for example) that we can't link to docs for.

**Comment by aomarks** [comment]
See also https://github.com/Polymer/polymer-analyzer/issues/691 (a couple issues with analyzer class output).

**Comment by aomarks** [comment]
Fixed by https://github.com/PolymerElements/iron-doc-viewer/pull/133
