### ISSUE TITLE
support for src=[Array]?

### ISSUE THREAD

**Issue by atotic** [PolymerElements/iron-doc-viewer#13]
Would there be support for src="[Array]" like core-component-page used to have?

Ex: sources='["google-map.html", "google-map-directions.html", "google-map-search.html"]'

**Comment by notwaldorf** [comment]
Is there any interest from anyone in the community to help implement this?

**Comment by notwaldorf** [comment]
(this may be fixed? It seems to work in `iron-component-page`: https://github.com/PolymerElements/paper-tabs/blob/master/index.html#L22)
