### ISSUE TITLE
Static methods (e.g. from mixins) not shown in API list

### ISSUE THREAD

**Issue by kevinpschaaf** [PolymerElements/iron-doc-viewer#130]
### Description
Static method members are not shown in API docs.

e.g. see https://www.polymer-project.org/2.0/docs/api/mixins/Polymer.PropertyEffects, check "Show Private" ([which should actually be "show protected"](https://github.com/PolymerElements/iron-doc-viewer/issues/117))

### Expected outcome
`addPropertyEffect` should be included in list: https://github.com/Polymer/polymer/blob/master/lib/mixins/property-effects.html#L2041-L2043

### Actual outcome
`addPropertyEffect` is not included

Version: `v2.0.0`

**Comment by aomarks** [comment]
Fixed by https://github.com/PolymerElements/iron-doc-viewer/pull/150
