### ISSUE TITLE
Elements without <dom-module> do not show up

### ISSUE THREAD

**Issue by atotic** [PolymerElements/iron-doc-viewer#14]
If <dom-module> is not defined, the documentation for the element does not show up.
Example: https://github.com/PolymerElements/iron-signals

**Comment by nevir** [comment]
Ah doh, we [just fixed JS comment attachment](https://github.com/Polymer/hydrolysis/commit/9a51a6cb09e1c53f3f12bd455396f0e9add7dfe9) for `Polymer()` calls, which is half of it

**Comment by nevir** [comment]
See https://github.com/PolymerElements/iron-signals/pull/2
