### ISSUE TITLE
Show the Inherited path

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/iron-doc-viewer#147]
After check the #146, I would like to propose add the "inherited path" from the inherited properties, methods, etc.

For example, in the `app-header-layout`:

<img width="810" alt="screen shot 2017-06-20 at 08 56 33" src="https://user-images.githubusercontent.com/1007051/27320402-61578aec-5596-11e7-8bc6-89f03bfaa909.png">

I would like to know that `resetLayout()` comes from `Polymer.AppLayoutBehavior`:

<img width="806" alt="screen shot 2017-06-20 at 08 59 08" src="https://user-images.githubusercontent.com/1007051/27320513-e507bccc-5596-11e7-873c-2292b7b6ea1b.png">

(I just wrote the text, the design could be improved.)

**Comment by samuelli** [comment]
@aomarks: this would also be solved by... jump to source!

**Comment by aomarks** [comment]
Fixed in https://github.com/PolymerElements/iron-doc-viewer/pull/149

**Comment by abdonrd** [comment]
@aomarks awesome, thanks! 🎉
