### ISSUE TITLE
Hide the API Reference when is empty

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/iron-doc-viewer#148]
After check the #146, I would like to propose hide the "API Reference" when is empty.

For example, in the [`app-toolbar`](https://aomarks-test-docs.appspot.com/app-layout.html#/elements/app-toolbar):

<img width="1110" alt="screen shot 2017-06-20 at 19 07 07" src="https://user-images.githubusercontent.com/1007051/27345951-bff4fbb6-55eb-11e7-83d1-f5918ca79c81.png">

**Comment by aomarks** [comment]
@abdonrd https://github.com/PolymerElements/iron-doc-viewer/pull/149 replaced the "API Reference" heading with an inline "show N protected" bar at the end of each section, when there are protected things to show. What do you think?

https://aomarks-test-docs.appspot.com/#/elements/array-selector#method-notifyPath

**Comment by abdonrd** [comment]
@aomarks it works for me, thanks! 👏 

One more thing... Now if you link to a protected method, the scroll and highlight doesn't work. Example:

https://aomarks-test-docs.appspot.com/#/elements/array-selector#method-_parseTemplate

**Comment by aomarks** [comment]
Yep, that's actually an existing issue, but do need to fix. Filed https://github.com/PolymerElements/iron-doc-viewer/issues/153.
