### ISSUE TITLE
Content not displaying as expected

### ISSUE THREAD

**Issue by jsilvermist** [PolymerElements/iron-doc-viewer#151]
## 1. Content changing after initial load
On https://aomarks-test-docs.appspot.com I'm only seeing `Classes` and the one `Namespace`, `Polymer` on the initial page load:

![screenshot 2017-06-21 17 39 03](https://user-images.githubusercontent.com/10246291/27407988-a352e1ae-56a8-11e7-8801-69ff61810230.png)

After clicking anything and then clicking back everything else appears:

![screenshot 2017-06-21 17 40 46](https://user-images.githubusercontent.com/10246291/27408026-c44f2d4a-56a8-11e7-9c5f-2d3d12b0d0bc.png)

## 2. Empty `iron-doc-summary` in Classes
Both on initial page load and after changing pages I noticed this empty element:

![image](https://user-images.githubusercontent.com/10246291/27408096-1b76a90e-56a9-11e7-862b-60894b152d5b.png)

**Comment by aomarks** [comment]
Fixed in https://github.com/PolymerElements/iron-doc-viewer/pull/152. We weren't respecting the `root-namespace` property in determining the initial view.
