### ISSUE TITLE
Information regarding License.

### ISSUE THREAD

**Issue by PSPawanSharma** [PolymerElements/iron-doc-viewer#172]
Hi Team,

I would like to use this component for development, but I could not locate any license file in the repository.

Can you suggest how to get the license information for using this component?

Thanks & regards,
Pawan

**Comment by TimvdLippe** [comment]
The license is visible at the top of every file, like: https://github.com/PolymerElements/iron-doc-viewer/blob/ec3f39ab5c31a40de638a8f4fac68b7dc2ecf1b4/iron-doc-viewer.html#L1-L9 The full license is available at http://polymer.github.io/LICENSE.txt

**Comment by PSPawanSharma** [comment]
Thanks for quick response. Thumbs up for that.

Regards,
Pawan
