### ISSUE TITLE
cdn.rawgit.com-hosted files will never change after first load

### ISSUE THREAD

**Issue by lucyllewy** [PolymerElements/iron-doc-viewer#23]
the current usage of rawgit prevents documentation pages from ever updating. Specifically the URL passed to hydrolysis-analyzer hardcodes the reference to `master`. Once the documentation page has been loaded just one time the file currently in master is cached by rawgit and will never change on the cdn thereafter:

per the rawgit faq (https://rawgit.com/faq#diff-between-rawgit-and-cdn):

> Requests to cdn.rawgit.com are routed through MaxCDN's super fast content delivery network, and are cached permanently the first time they're loaded. This results in the best performance and reduces load on RawGit and on GitHub, but it means that reloading won't fetch new changes from GitHub.

and further down (https://rawgit.com/faq#cdn-ttl):

> The CDN caches files permanently based on their path. It ignores query strings.
> ...
> To ensure that the CDN always serves the version of the file you want, use a git tag or commit ref in the file's path instead of a branch name, and update the URL if you push a new version of the file.

Ideally the `_srcChanged` function would be able to load the latest tagged release and use the tag in the path to the file when loading for analysis. This would allow future updates to a component to be reflected in the documentation generated, which cannot happen right now due to use of the `master` reference combined with rawgit's cdn.

**Comment by lucyllewy** [comment]
there's a pull request in #25

**Comment by notwaldorf** [comment]
I don't think this is still an issue, but please re-open if it is!
