### ISSUE TITLE
Default value not showing if the property is false

### ISSUE THREAD

**Issue by drxcheng** [PolymerElements/iron-doc-viewer#26]
This does not work:

```
iAmFalse: {
  type: Boolean,
  value: false
}
```

This works:

```
iAmFalse: {
  type: Boolean,
  value: 'false'
}
```

I am actually using it in 'iron-component-page'

**Comment by atotic** [comment]
@drxcheng please clarify. This works:

```
  iAmTrue: {
    type: Boolean,
    value: true
  }
```

**Comment by drxcheng** [comment]
@atotic I updated the title and description. Sorry for the confusion.

**Comment by atotic** [comment]
This happens because:
`<span id="default" hidden$="{{!descriptor.default}}">default:`
when descriptor is false, nothing gets shown.
