### ISSUE TITLE
Doc for the return values for methods with no parameters don't show up

### ISSUE THREAD

**Issue by morethanreal** [PolymerElements/iron-doc-viewer#29]
``` js
/**
 * @return {Boolean} true always
 */
fooMethod: function() {
  return true;
}
```

This does not show the return value doc, but the following does:

``` js
/**
 * @return {Boolean} true always
 */
fooMethod: function(bar) {
  return true;
}
```

**Comment by mbleigh** [comment]
I think this is likely a [hydrolysis](https://github.com/polymer/hydrolysis) -- doc viewer just shows what it gets from there

**Comment by morethanreal** [comment]
cc @garlicnation ?

**Comment by atotic** [comment]
This is an iron-doc-viewer issue. Return value is shown inside 

```
<ol id="params" hidden$="{{_computeHideParams(descriptor)}}">
```

No params, no return value
