### ISSUE TITLE
In files with multiple dom-modules, the definition of the first one is shown on all elements

### ISSUE THREAD

**Issue by nhnb** [PolymerElements/iron-doc-viewer#36]
If mutliples &lt:dom-module&gt; are defined in a single file, the element description of the first entry is shown for all elements. The properties section of the correct element is shown. So only the element description is wrong.

The attached screenshot shows the element description of &lt;leaflet-icon&gt; instead of the selected &lt;leaflet-marker&gt; It is based on this file: https://github.com/nhnb/leaflet-map/blob/0.9.0/leaflet-marker.html

![bildschirmfoto vom 2015-05-28 02 26 41](https://cloud.githubusercontent.com/assets/364184/7850326/01d344f6-04e1-11e5-8170-4cbb98722662.png)

**Comment by atotic** [comment]
Waiting on https://github.com/PolymerLabs/dom5/pull/20 
Fix it with nodeWalkAllPrior

**Comment by atotic** [comment]
Fixed in hydrolysis
