### ISSUE TITLE
Set the website of this GitHub repo to the Atmopshere package

### ISSUE THREAD

**Issue by dandv** [PolymerElements/iron-doc-viewer#39]
Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

I guess this repo powers https://elements.polymer-project.org/elements/paper-input

**Comment by notwaldorf** [comment]
I'm not sure what this screenshot is for, but it's not about Polymer elements :)

Closing this. Please re-open if you have more details.

**Comment by dandv** [comment]
Salut Monica.

It's an example of how to set set the website of the GitHub repo.

**Comment by dandv** [comment]
Is https://github.com/PolymerElements/polymer-starter-kit a better example? :)

**Comment by notwaldorf** [comment]
Oh yes, we're on it. We're going to be updating the URLs soon. Thanks!
