### ISSUE TITLE
Display null default values

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-doc-viewer#48]
If properties define a `null` default value, this shows up as `default:`. This can be misleading when `readOnly` or other pragmas are used:

![screen shot 2015-06-11 at 3 29 13 pm](https://cloud.githubusercontent.com/assets/238208/8119935/b0b3c662-104e-11e5-86b8-99e98b06a5df.png)

In this case it looks like the default value is `readyOnly` :(

**Comment by FredKSchott** [comment]
Fixed in df35dfb1dfefd7ed71b0feca1045a608653e6149
