### ISSUE TITLE
Allow deep hash linking to specific properties/methods in API docs

### ISSUE THREAD

**Issue by kevinpschaaf** [PolymerElements/iron-doc-viewer#53]
In responding to user issues, it would be very helpful to be able to deep-link directly to a specific property or method's API documentation.

e.g. rather than telling a user:
- Open http://polymer.github.io/polymer/
- Hit ctrl-F
- Type "scopeSubtree"
- See docs for the `scopeSubtree` method

We'd like to be able to just say:
- See docs for `scopeSubtree` here: http://polymer.github.io/polymer/#scopeSubtree

**Comment by arthurevans** [comment]
Also: specific elements (like dom-bind) which are currently hidden under the pulldown. Yes, yes, yes.

**Comment by atotic** [comment]
I suggest if you are using this to use my router in iron-component-page and the polymer-catalog. You could develop a "document routing element" that encapsulates a lot of linking work.

**Comment by notwaldorf** [comment]
Done!
