### ISSUE TITLE
Document notifying property's `prop-changed` event under Events section

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-doc-viewer#67]
Discussion from https://github.com/PolymerElements/iron-media-query/pull/32.

It's easy to forget properties that `notify: true` also fire a _prop_-changed event. It would be nice
to explicitly document these in the events section of API docs so users don't forget and/or they 
need that hook. I did!

**Comment by justinfagnani** [comment]
Closing in favor of hydrolysis bug
