### ISSUE TITLE
Inherited events from behavior are missing descriptions

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-doc-viewer#74]
iron-selector has the inherited events, however they're missing descriptions:

<img width="1116" alt="screen shot 2015-12-15 at 7 05 51 pm" src="https://cloud.githubusercontent.com/assets/238208/11830988/36b98b86-a35f-11e5-833a-c411fe2dc186.png">

(https://elements.polymer-project.org/elements/iron-selector)

The descriptions from `Polymer.IronSelectableBehavior` are not brought in.

<img width="1109" alt="screen shot 2015-12-15 at 7 05 46 pm" src="https://cloud.githubusercontent.com/assets/238208/11830990/3c4c1bf4-a35f-11e5-8acb-787fb4ce9460.png">

(https://elements.polymer-project.org/elements/iron-selector?active=Polymer.IronSelectableBehavior)

cc @garlicnation

**Comment by arthurevans** [comment]
Interesting. Looks like the descriptions from `IronMutliSelectableBehavior` are showing up, but not the once-removed events from `IronSelectableBehavior`. Something off with the way hydrolysis collates inherited stuff?

**Comment by garlicnation** [comment]
Fixed on hydrolysis@master

**Comment by notwaldorf** [comment]
This will be fixed when https://github.com/Polymer/hydrolysis/pull/211/files lands, so I'll close this issue (since there's nothing we can do here)
