### ISSUE TITLE
scrollToAnchor takes in hash but uses window.location.hash

### ISSUE THREAD

**Issue by purdrew** [PolymerElements/iron-doc-viewer#86]
### Description

I was hoping to use the `scrollToAnchor()` method to scroll to a specific anchor in my docs. The method takes in a `hash` parameter which I assumed it would use as the target anchor to scroll into view. However, looking at the [code](https://github.com/PolymerElements/iron-doc-viewer/blob/master/iron-doc-viewer.html#L216) it ends up pulling the hash from `window.location.hash` instead.
### Expected outcome

Should use the passed in hash if it is specified.
### Actual outcome

Uses `window.location.hash` regardless of passed in hash.
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by aomarks** [comment]
This is fixed in the 3.0 release.
